apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: sonarqube
  name: sonarqube
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
        - name: sonarqube
          image: sonarqube:latest
#          command:
#            - sysctl
#            - -w
#            - vm.max_map_count=262144
#          securityContext:
#            privileged: true
          resources:
            requests:
              cpu: 500m
              memory: 4Gi
            limits:
              cpu: 2000m
              memory: 4Gi
          volumeMounts:
            - mountPath: "/opt/sonarqube/data/"
              name: sonar-data
            - mountPath: "/opt/sonarqube/extensions/"
              name: sonar-extensions
          env:
            - name: ES_JAVA_OPTS
              value: -Xms2g -Xmx2g
            - name: SONARQUBE_WEB_JVM_OPTS
              value: -Xmx2048m
            - name: "SONARQUBE_JDBC_USERNAME"
              value: "devopsadmin@tbct-devops"
            - name: "SONARQUBE_JDBC_URL"
              value: "jdbc:postgresql://tbct-devops.postgres.database.azure.com:5432/sonardb?sslmode=require"
            - name: "SONARQUBE_JDBC_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: password
          ports:
            - containerPort: 9000
              protocol: TCP
      volumes:
        - name: sonar-data
          persistentVolumeClaim:
            claimName: sonar-data
        - name: sonar-extensions
          persistentVolumeClaim:
            claimName: sonar-extensions